// ⚙️ 本文件由 scripts/gen-static-themes.mjs 生成 —— **不要手改**。
//
// 它是 global.css 里那 11 套经典主题（中国风 / 魔兽 / 赛博朋克 …）的配色条目：
// 那些主题本来靠 :root[data-theme="…"] 切换，而设置里的配色下拉读的是 themeLibrary，
// 所以要先变成条目才在界面上出现。
//
// ⚠️ 用户从列表里选这些主题时走的是 applyPaletteTheme(entry.palette)（内联注入 :root），
//    **不会设 data-theme 属性** —— 所以列表里真正生效的是本文件的值，必须与 CSS 同步。
//
// 色值的源头只有一个：global.css 里那几个主题块。改配色请改那边（或改生成器的种子/参数），
// 然后重跑：node scripts/gen-static-themes.mjs --apply
import type { ThemeEntry } from "./themeLibrary";

export const staticThemeEntries: ThemeEntry[] = [
  {
    id: "s-default",
    name: "default",
    zh: "默认暗色",
    desc: "Playday 默认（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#111318",
      foreground: "#dde2f0",
      card: "#1d1f25",
      cardForeground: "#dde2f0",
      primary: "#1d71ea",
      primaryForeground: "#ffffff",
      secondary: "#282a2f",
      secondaryForeground: "#dde2f0",
      muted: "#0c0e13",
      mutedForeground: "#c1c6d4",
      border: "#46494f",
      ring: "#1d71ea",
      bgBase: "#111318",
      bgTop: "#1d1f25",
      bgSidebar: "#191b21",
      bgPanel: "#1d1f25",
      bgItemHover: "#282a2f",
      bgItemActive: "#32353a",
      bgInput: "#0c0e13",
      borderStrong: "#8e9198",
      textPrimary: "#dde2f0",
      textSecondary: "#c1c6d4",
      textDim: "#8b919d",
      accent: "#1d71ea",
      accentHover: "#3687ff",
      accentSoft: "color-mix(in srgb, #1d71ea 16%, transparent)",
      success: "#6ccb71",
      warning: "#edb627",
      danger: "#ff9c8d",
    },
  },
  {
    id: "s-cartoon",
    name: "cartoon",
    zh: "卡通",
    desc: "明亮、圆润、暖色（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#fff9ec",
      foreground: "#221b0a",
      card: "#f3ede0",
      cardForeground: "#221b0a",
      primary: "#fc8759",
      primaryForeground: "#630000",
      secondary: "#eee8db",
      secondaryForeground: "#221b0a",
      muted: "#fffff2",
      mutedForeground: "#4e4634",
      border: "#ccc6b9",
      ring: "#fc8759",
      bgBase: "#fff9ec",
      bgTop: "#f3ede0",
      bgSidebar: "#f9f3e6",
      bgPanel: "#f3ede0",
      bgItemHover: "#eee8db",
      bgItemActive: "#e8e2d5",
      bgInput: "#fffff2",
      borderStrong: "#7c766b",
      textPrimary: "#221b0a",
      textSecondary: "#4e4634",
      textDim: "#756c59",
      accent: "#fc8759",
      accentHover: "#e47143",
      accentSoft: "color-mix(in srgb, #fc8759 16%, transparent)",
      success: "#07781f",
      warning: "#935f00",
      danger: "#b81611",
    },
  },
  {
    id: "s-cyberpunk",
    name: "cyberpunk",
    zh: "赛博朋克",
    desc: "暗底霓虹、发光边（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#0f131c",
      foreground: "#dce3f0",
      card: "#1b1f29",
      cardForeground: "#dce3f0",
      primary: "#00f0ff",
      primaryForeground: "#00393e",
      secondary: "#252a34",
      secondaryForeground: "#dce3f0",
      muted: "#0a0e17",
      mutedForeground: "#c1c6d4",
      border: "#41495a",
      ring: "#00f0ff",
      bgBase: "#0f131c",
      bgTop: "#1b1f29",
      bgSidebar: "#171b25",
      bgPanel: "#1b1f29",
      bgItemHover: "#252a34",
      bgItemActive: "#30353f",
      bgInput: "#0a0e17",
      borderStrong: "#8791a5",
      textPrimary: "#dce3f0",
      textSecondary: "#c1c6d4",
      textDim: "#8b919d",
      accent: "#00f0ff",
      accentHover: "#93ffff",
      accentSoft: "color-mix(in srgb, #00f0ff 16%, transparent)",
      success: "#62fc71",
      warning: "#ffefcd",
      danger: "#ff4032",
    },
  },
  {
    id: "s-memphis",
    name: "memphis",
    zh: "孟菲斯",
    desc: "几何原色、活泼（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#fff8ee",
      foreground: "#231a0b",
      card: "#f4ede3",
      cardForeground: "#231a0b",
      primary: "#ff4d6d",
      primaryForeground: "#570015",
      secondary: "#eee7dd",
      secondaryForeground: "#231a0b",
      muted: "#fffef8",
      mutedForeground: "#504535",
      border: "#ccc5bc",
      ring: "#ff4d6d",
      bgBase: "#fff8ee",
      bgTop: "#f4ede3",
      bgSidebar: "#faf3e9",
      bgPanel: "#f4ede3",
      bgItemHover: "#eee7dd",
      bgItemActive: "#e8e1d8",
      bgInput: "#fffef8",
      borderStrong: "#7c766e",
      textPrimary: "#231a0b",
      textSecondary: "#504535",
      textDim: "#776b5a",
      accent: "#ff4d6d",
      accentHover: "#e63259",
      accentSoft: "color-mix(in srgb, #ff4d6d 16%, transparent)",
      success: "#00791c",
      warning: "#916000",
      danger: "#bd0000",
    },
  },
  {
    id: "s-neumorphism",
    name: "neumorphism",
    zh: "新拟态",
    desc: "柔和浮雕、浅灰（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#f5faff",
      foreground: "#101d29",
      card: "#eaeef3",
      cardForeground: "#101d29",
      primary: "#80a9ec",
      primaryForeground: "#0a2d66",
      secondary: "#e4e9ee",
      secondaryForeground: "#101d29",
      muted: "#fbffff",
      mutedForeground: "#3a4856",
      border: "#c2c7cc",
      ring: "#80a9ec",
      bgBase: "#f5faff",
      bgTop: "#eaeef3",
      bgSidebar: "#eff4f9",
      bgPanel: "#eaeef3",
      bgItemHover: "#e4e9ee",
      bgItemActive: "#dee3e8",
      bgInput: "#fbffff",
      borderStrong: "#74777c",
      textPrimary: "#101d29",
      textSecondary: "#3a4856",
      textDim: "#606f7e",
      accent: "#80a9ec",
      accentHover: "#6b93d5",
      accentSoft: "color-mix(in srgb, #80a9ec 16%, transparent)",
      success: "#37733a",
      warning: "#876400",
      danger: "#a04035",
    },
  },
  {
    id: "s-comic",
    name: "comic",
    zh: "美漫",
    desc: "粗黑描边、网点（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#fcfaed",
      foreground: "#1f1c0b",
      card: "#f0eee1",
      cardForeground: "#1f1c0b",
      primary: "#d01d34",
      primaryForeground: "#ffffff",
      secondary: "#ebe9dc",
      secondaryForeground: "#1f1c0b",
      muted: "#fffff3",
      mutedForeground: "#4a4735",
      border: "#c9c7ba",
      ring: "#d01d34",
      bgBase: "#fcfaed",
      bgTop: "#f0eee1",
      bgSidebar: "#f6f4e7",
      bgPanel: "#f0eee1",
      bgItemHover: "#ebe9dc",
      bgItemActive: "#e5e3d6",
      bgInput: "#fffff3",
      borderStrong: "#79776c",
      textPrimary: "#1f1c0b",
      textSecondary: "#4a4735",
      textDim: "#716e5a",
      accent: "#d01d34",
      accentHover: "#b40022",
      accentSoft: "color-mix(in srgb, #d01d34 16%, transparent)",
      success: "#39723d",
      warning: "#8c6300",
      danger: "#ac3700",
    },
  },
  {
    id: "s-ghibli",
    name: "ghibli",
    zh: "吉卜力",
    desc: "柔和自然色（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#fdfaed",
      foreground: "#201b0a",
      card: "#f1eee1",
      cardForeground: "#201b0a",
      primary: "#6d9a5e",
      primaryForeground: "#043000",
      secondary: "#ebe8dc",
      secondaryForeground: "#201b0a",
      muted: "#fffff2",
      mutedForeground: "#4b4734",
      border: "#cac7ba",
      ring: "#6d9a5e",
      bgBase: "#fdfaed",
      bgTop: "#f1eee1",
      bgSidebar: "#f7f4e7",
      bgPanel: "#f1eee1",
      bgItemHover: "#ebe8dc",
      bgItemActive: "#e6e3d6",
      bgInput: "#fffff2",
      borderStrong: "#7a776c",
      textPrimary: "#201b0a",
      textSecondary: "#4b4734",
      textDim: "#726d5a",
      accent: "#6d9a5e",
      accentHover: "#59854a",
      accentSoft: "color-mix(in srgb, #6d9a5e 16%, transparent)",
      success: "#2e7534",
      warning: "#886400",
      danger: "#9c443a",
    },
  },
  {
    id: "s-chinese",
    name: "chinese",
    zh: "中国风",
    desc: "墨红、金、宣纸（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#fff9eb",
      foreground: "#211b0a",
      card: "#f3ede0",
      cardForeground: "#211b0a",
      primary: "#9e1b32",
      primaryForeground: "#ffffff",
      secondary: "#eee8da",
      secondaryForeground: "#211b0a",
      muted: "#fffff1",
      mutedForeground: "#4e4634",
      border: "#ccc6b9",
      ring: "#9e1b32",
      bgBase: "#fff9eb",
      bgTop: "#f3ede0",
      bgSidebar: "#f9f3e5",
      bgPanel: "#f3ede0",
      bgItemHover: "#eee8da",
      bgItemActive: "#e8e2d4",
      bgInput: "#fffff1",
      borderStrong: "#7c766a",
      textPrimary: "#211b0a",
      textSecondary: "#4e4634",
      textDim: "#756c59",
      accent: "#9e1b32",
      accentHover: "#850021",
      accentSoft: "color-mix(in srgb, #9e1b32 16%, transparent)",
      success: "#287630",
      warning: "#896400",
      danger: "#a23816",
    },
  },
  {
    id: "s-wow",
    name: "wow",
    zh: "魔兽世界",
    desc: "羊皮纸暗底 + 金（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#17130d",
      foreground: "#eae1d4",
      card: "#231f19",
      cardForeground: "#eae1d4",
      primary: "#c8a44e",
      primaryForeground: "#482900",
      secondary: "#2e2923",
      secondaryForeground: "#eae1d4",
      muted: "#110d08",
      mutedForeground: "#cec5b8",
      border: "#4d4841",
      ring: "#c8a44e",
      bgBase: "#17130d",
      bgTop: "#231f19",
      bgSidebar: "#1f1b15",
      bgPanel: "#231f19",
      bgItemHover: "#2e2923",
      bgItemActive: "#39342d",
      bgInput: "#110d08",
      borderStrong: "#959089",
      textPrimary: "#eae1d4",
      textSecondary: "#cec5b8",
      textDim: "#988f83",
      accent: "#c8a44e",
      accentHover: "#deba64",
      accentSoft: "color-mix(in srgb, #c8a44e 16%, transparent)",
      success: "#58a45c",
      warning: "#dd985c",
      danger: "#ff9c8d",
    },
  },
  {
    id: "s-lol",
    name: "lol",
    zh: "英雄联盟",
    desc: "符文之地午夜 + 金（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#12121c",
      foreground: "#e0e1f0",
      card: "#1e1e29",
      cardForeground: "#e0e1f0",
      primary: "#c8aa6e",
      primaryForeground: "#442b00",
      secondary: "#292934",
      secondaryForeground: "#e0e1f0",
      muted: "#0d0d17",
      mutedForeground: "#c4c5d4",
      border: "#474756",
      ring: "#c8aa6e",
      bgBase: "#12121c",
      bgTop: "#1e1e29",
      bgSidebar: "#1a1a25",
      bgPanel: "#1e1e29",
      bgItemHover: "#292934",
      bgItemActive: "#33343f",
      bgInput: "#0d0d17",
      borderStrong: "#8e8f9e",
      textPrimary: "#e0e1f0",
      textSecondary: "#c4c5d4",
      textDim: "#8f8f9d",
      accent: "#c8aa6e",
      accentHover: "#dec083",
      accentSoft: "color-mix(in srgb, #c8aa6e 16%, transparent)",
      success: "#72b274",
      warning: "#d99f7b",
      danger: "#ff9c8d",
    },
  },
  {
    id: "s-pubg",
    name: "pubg",
    zh: "绝地求生",
    desc: "军绿 / 卡其 + 炭灰（经典主题，色值由 MD3 生成）",
    category: "经典主题",
    palette: {
      background: "#141410",
      foreground: "#e4e4d5",
      card: "#20201c",
      cardForeground: "#e4e4d5",
      primary: "#b8a06e",
      primaryForeground: "#412c00",
      secondary: "#2a2a26",
      secondaryForeground: "#e4e4d5",
      muted: "#0e0e0b",
      mutedForeground: "#c8c8b9",
      border: "#474742",
      ring: "#b8a06e",
      bgBase: "#141410",
      bgTop: "#20201c",
      bgSidebar: "#1c1c18",
      bgPanel: "#20201c",
      bgItemHover: "#2a2a26",
      bgItemActive: "#353531",
      bgInput: "#0e0e0b",
      borderStrong: "#91918c",
      textPrimary: "#e4e4d5",
      textSecondary: "#c8c8b9",
      textDim: "#929284",
      accent: "#b8a06e",
      accentHover: "#ceb683",
      accentSoft: "color-mix(in srgb, #b8a06e 16%, transparent)",
      success: "#65af68",
      warning: "#e39856",
      danger: "#ff9c8d",
    },
  },
];
