@echo off
REM ============================================================================
REM  build.bat - Compile GameSaveHelper.exe with MSVC (static CRT, single file)
REM  Just double-click this file, or run it from a command prompt.
REM ============================================================================
setlocal enabledelayedexpansion

set "ROOT=%~dp0"
set "SRCDIR=%ROOT%src"

REM ---------- locate MSVC ----------
set "VCBASE=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
if not exist "%VCBASE%" set "VCBASE=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC"
if not exist "%VCBASE%" set "VCBASE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC"
if not exist "%VCBASE%" set "VCBASE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC"
if not exist "%VCBASE%" (
    call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.err-msvc
    exit /b 3
)

set "VCV="
for /f "delims=" %%i in ('dir /b /o-n "%VCBASE%" 2^>nul') do (
    if not defined VCV set "VCV=%%i"
)
if not defined VCV (
    call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.err-msvc-version
    exit /b 3
)

REM ---------- locate Windows SDK ----------
set "SDKB=C:\Program Files (x86)\Windows Kits\10"
if not exist "%SDKB%" (
    call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.err-sdk
    exit /b 3
)
set "SDKV="
for /f "delims=" %%i in ('dir /b /o-n "%SDKB%\Include" 2^>nul') do (
    if not defined SDKV set "SDKV=%%i"
)
if not defined SDKV (
    call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.err-sdk-version
    exit /b 3
)

set "VCDIR=%VCBASE%\%VCV%"
call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.toolchain "%VCV%" "%SDKV%"

set "PATH=%VCDIR%\bin\Hostx64\x64;%SDKB%\bin\%SDKV%\x64;%PATH%"
set "INCLUDE=%VCDIR%\include;%SDKB%\Include\%SDKV%\ucrt;%SDKB%\Include\%SDKV%\um;%SDKB%\Include\%SDKV%\shared;%SDKB%\Include\%SDKV%\winrt"
set "LIB=%VCDIR%\lib\x64;%SDKB%\Lib\%SDKV%\ucrt\x64;%SDKB%\Lib\%SDKV%\um\x64"

REM ---------- sync template + icon into src (compiled as resources) ----------
if not exist "%ROOT%template\GameSaveHelper.nsi" (
    call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.err-nsi "%ROOT%template\GameSaveHelper.nsi"
    exit /b 3
)
copy /y "%ROOT%template\GameSaveHelper.nsi" "%SRCDIR%\template.nsi" >nul
REM Main icon: prefer assets\icon.ico (generated by scripts\gen-app-icon.mjs),
REM otherwise fall back to the icon that ships with NSIS.
if exist "%ROOT%assets\icon.ico" (
    copy /y "%ROOT%assets\icon.ico" "%SRCDIR%\app.ico" >nul
) else if exist "%ROOT%nsis\Contrib\Graphics\Icons\modern-install.ico" (
    copy /y "%ROOT%nsis\Contrib\Graphics\Icons\modern-install.ico" "%SRCDIR%\app.ico" >nul
)

pushd "%SRCDIR%"

call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.step-resource
rc.exe /nologo /fo resource.res resource.rc
if errorlevel 1 (
    call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.err-rc
    popd
    exit /b 4
)

call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.step-compile
cl.exe /nologo /utf-8 /O2 /Oi /GL /Gy /MT /EHsc /std:c++17 /W3 ^
    /DUNICODE /D_UNICODE /DWIN32 /D_WINDOWS /DNDEBUG ^
    /c /Fo:GameSaveHelper.obj GameSaveHelper.cpp
if errorlevel 1 (
    call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.err-cl
    popd
    exit /b 4
)

call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.step-link
link.exe /nologo /LTCG /OPT:REF /OPT:ICF /SUBSYSTEM:WINDOWS /MACHINE:X64 ^
    /OUT:"%ROOT%GameSaveHelper.exe" ^
    GameSaveHelper.obj resource.res ^
    user32.lib gdi32.lib comctl32.lib comdlg32.lib shell32.lib shlwapi.lib ole32.lib advapi32.lib
if errorlevel 1 (
    call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.err-link
    popd
    exit /b 4
)

popd

if exist "%ROOT%GameSaveHelper.exe" (
    echo.
    for %%F in ("%ROOT%GameSaveHelper.exe") do call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.ok "%%~fF" "%%~zF"
    echo.
    exit /b 0
)

call node "%~dp0..\..\scripts\bat-msg.mjs" gamesavehelper.err-no-exe
exit /b 4
